[package]
name = "wasi-nn-onnx-test"
version = "0.0.1"
authors = ["Ville Heikkilä"]

[dependencies]
image2tensor = "0.3.1"
wasi-nn = "0.6.0"

[profile.release-lto]
inherits = "release"
lto = true
strip = "debuginfo"

[profile.release-lto.build-override]
opt-level = 3
codegen-units = 256
debug = false
debug-assertions = false
